# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 199, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 78, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 78, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 42, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 199, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 78, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 78, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 42, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(93, 78, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 78, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 42, 55))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 31, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 45, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 63, 83))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(40, 45, 52);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.horizontalFrame.setFont(font)
        self.horizontalFrame.setStyleSheet("background-color: rgb(60, 63, 83);")
        self.horizontalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToggleFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.ToggleFrame.setMaximumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.ToggleFrame.setFont(font)
        self.ToggleFrame.setStyleSheet("background-color: rgb(60, 63, 83);")
        self.ToggleFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ToggleFrame.setObjectName("ToggleFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ToggleFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MenuBttn = QtWidgets.QPushButton(self.ToggleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuBttn.sizePolicy().hasHeightForWidth())
        self.MenuBttn.setSizePolicy(sizePolicy)
        self.MenuBttn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.MenuBttn.setFont(font)
        self.MenuBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(213, 72, 89);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171, 72, 101);\n"
"}")
        self.MenuBttn.setObjectName("MenuBttn")
        self.horizontalLayout_3.addWidget(self.MenuBttn)
        self.SettingBttn = QtWidgets.QPushButton(self.ToggleFrame)
        self.SettingBttn.setMaximumSize(QtCore.QSize(70, 40))
        self.SettingBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(213, 72, 89);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(171, 72, 101);\n"
"}")
        self.SettingBttn.setObjectName("SettingBttn")
        self.horizontalLayout_3.addWidget(self.SettingBttn)
        self.horizontalLayout.addWidget(self.ToggleFrame)
        self.TopFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.TopFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.horizontalLayout.addWidget(self.TopFrame)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Content.sizePolicy().hasHeightForWidth())
        self.Content.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.Content.setFont(font)
        self.Content.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MenuFrane = QtWidgets.QFrame(self.Content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuFrane.sizePolicy().hasHeightForWidth())
        self.MenuFrane.setSizePolicy(sizePolicy)
        self.MenuFrane.setMinimumSize(QtCore.QSize(70, 0))
        self.MenuFrane.setMaximumSize(QtCore.QSize(70, 16777215))
        self.MenuFrane.setStyleSheet("background-color: rgb(60, 63, 83);")
        self.MenuFrane.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuFrane.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuFrane.setObjectName("MenuFrane")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MenuFrane)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MenuBttnFrame = QtWidgets.QFrame(self.MenuFrane)
        self.MenuBttnFrame.setMinimumSize(QtCore.QSize(70, 0))
        self.MenuBttnFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuBttnFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBttnFrame.setObjectName("MenuBttnFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MenuBttnFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MenuBrowse = QtWidgets.QPushButton(self.MenuBttnFrame)
        self.MenuBrowse.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.MenuBrowse.setFont(font)
        self.MenuBrowse.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.MenuBrowse.setObjectName("MenuBrowse")
        self.verticalLayout_4.addWidget(self.MenuBrowse)
        self.MenuProcess = QtWidgets.QPushButton(self.MenuBttnFrame)
        self.MenuProcess.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.MenuProcess.setFont(font)
        self.MenuProcess.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.MenuProcess.setObjectName("MenuProcess")
        self.verticalLayout_4.addWidget(self.MenuProcess)
        self.MenuAnal = QtWidgets.QPushButton(self.MenuBttnFrame)
        self.MenuAnal.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.MenuAnal.setFont(font)
        self.MenuAnal.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.MenuAnal.setObjectName("MenuAnal")
        self.verticalLayout_4.addWidget(self.MenuAnal)
        self.MenuSegment = QtWidgets.QPushButton(self.MenuBttnFrame)
        self.MenuSegment.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.MenuSegment.setFont(font)
        self.MenuSegment.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.MenuSegment.setObjectName("MenuSegment")
        self.verticalLayout_4.addWidget(self.MenuSegment)
        self.verticalLayout_3.addWidget(self.MenuBttnFrame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.MenuFrane)
        self.PagesFrame = QtWidgets.QFrame(self.Content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PagesFrame.sizePolicy().hasHeightForWidth())
        self.PagesFrame.setSizePolicy(sizePolicy)
        self.PagesFrame.setStyleSheet("background-color: rgb(93, 78, 106);\n"
"")
        self.PagesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PagesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PagesFrame.setObjectName("PagesFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.PagesFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PagesWidget = QtWidgets.QStackedWidget(self.PagesFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PagesWidget.sizePolicy().hasHeightForWidth())
        self.PagesWidget.setSizePolicy(sizePolicy)
        self.PagesWidget.setStyleSheet("    color: rgb(250, 199, 178);")
        self.PagesWidget.setObjectName("PagesWidget")
        self.SettingsPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsPage.sizePolicy().hasHeightForWidth())
        self.SettingsPage.setSizePolicy(sizePolicy)
        self.SettingsPage.setObjectName("SettingsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SettingsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BrowseBttn_2 = QtWidgets.QPushButton(self.SettingsPage)
        self.BrowseBttn_2.setMinimumSize(QtCore.QSize(120, 40))
        self.BrowseBttn_2.setMaximumSize(QtCore.QSize(120, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.BrowseBttn_2.setFont(font)
        self.BrowseBttn_2.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.BrowseBttn_2.setObjectName("BrowseBttn_2")
        self.gridLayout.addWidget(self.BrowseBttn_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.PathLine_2 = QtWidgets.QLineEdit(self.SettingsPage)
        self.PathLine_2.setMinimumSize(QtCore.QSize(0, 40))
        self.PathLine_2.setMaximumSize(QtCore.QSize(750, 40))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.PathLine_2.setFont(font)
        self.PathLine_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PathLine_2.setStyleSheet("color: rgb(250, 199, 178);")
        self.PathLine_2.setInputMask("")
        self.PathLine_2.setObjectName("PathLine_2")
        self.gridLayout.addWidget(self.PathLine_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.SettingsPage)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.PagesWidget.addWidget(self.SettingsPage)
        self.BrowsePage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BrowsePage.sizePolicy().hasHeightForWidth())
        self.BrowsePage.setSizePolicy(sizePolicy)
        self.BrowsePage.setObjectName("BrowsePage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.BrowsePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BrowseBttn = QtWidgets.QPushButton(self.BrowsePage)
        self.BrowseBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.BrowseBttn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.BrowseBttn.setFont(font)
        self.BrowseBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.BrowseBttn.setObjectName("BrowseBttn")
        self.verticalLayout.addWidget(self.BrowseBttn)
        self.PathLine = QtWidgets.QLineEdit(self.BrowsePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathLine.sizePolicy().hasHeightForWidth())
        self.PathLine.setSizePolicy(sizePolicy)
        self.PathLine.setMinimumSize(QtCore.QSize(0, 50))
        self.PathLine.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.PathLine.setFont(font)
        self.PathLine.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PathLine.setStyleSheet("color: rgb(250, 199, 178);")
        self.PathLine.setInputMask("")
        self.PathLine.setObjectName("PathLine")
        self.verticalLayout.addWidget(self.PathLine)
        self.LoadBttn = QtWidgets.QPushButton(self.BrowsePage)
        self.LoadBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.LoadBttn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.LoadBttn.setFont(font)
        self.LoadBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.LoadBttn.setObjectName("LoadBttn")
        self.verticalLayout.addWidget(self.LoadBttn)
        self.ContentTable = QtWidgets.QTableWidget(self.BrowsePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContentTable.sizePolicy().hasHeightForWidth())
        self.ContentTable.setSizePolicy(sizePolicy)
        self.ContentTable.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.ContentTable.setStyleSheet("QTableWidget::item {\n"
"    background-color: rgb(171, 73, 101);\n"
"}\n"
"QHeaderView::section{\n"
"    Background-color:rgb(213, 72, 89);\n"
"}")
        self.ContentTable.setObjectName("ContentTable")
        self.ContentTable.setColumnCount(0)
        self.ContentTable.setRowCount(0)
        self.verticalLayout.addWidget(self.ContentTable)
        self.PagesWidget.addWidget(self.BrowsePage)
        self.PreProcessedPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreProcessedPage.sizePolicy().hasHeightForWidth())
        self.PreProcessedPage.setSizePolicy(sizePolicy)
        self.PreProcessedPage.setObjectName("PreProcessedPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PreProcessedPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DAPIBttn = QtWidgets.QPushButton(self.PreProcessedPage)
        self.DAPIBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.DAPIBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.DAPIBttn.setObjectName("DAPIBttn")
        self.gridLayout_3.addWidget(self.DAPIBttn, 0, 0, 1, 1)
        self.PreProcessLabel = QtWidgets.QLabel(self.PreProcessedPage)
        self.PreProcessLabel.setMinimumSize(QtCore.QSize(512, 512))
        self.PreProcessLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.PreProcessLabel.setText("")
        self.PreProcessLabel.setObjectName("PreProcessLabel")
        self.gridLayout_3.addWidget(self.PreProcessLabel, 0, 1, 2, 2)
        self.StartBttn = QtWidgets.QPushButton(self.PreProcessedPage)
        self.StartBttn.setMinimumSize(QtCore.QSize(150, 50))
        self.StartBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.StartBttn.setObjectName("StartBttn")
        self.gridLayout_3.addWidget(self.StartBttn, 0, 3, 1, 1)
        self.AlxBttn = QtWidgets.QPushButton(self.PreProcessedPage)
        self.AlxBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.AlxBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.AlxBttn.setObjectName("AlxBttn")
        self.gridLayout_3.addWidget(self.AlxBttn, 1, 0, 1, 1)
        self.PrevStepBttn = QtWidgets.QPushButton(self.PreProcessedPage)
        self.PrevStepBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.PrevStepBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.PrevStepBttn.setObjectName("PrevStepBttn")
        self.gridLayout_3.addWidget(self.PrevStepBttn, 2, 1, 1, 1)
        self.ForwStepBttn = QtWidgets.QPushButton(self.PreProcessedPage)
        self.ForwStepBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.ForwStepBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.ForwStepBttn.setObjectName("ForwStepBttn")
        self.gridLayout_3.addWidget(self.ForwStepBttn, 2, 2, 1, 1)
        self.PagesWidget.addWidget(self.PreProcessedPage)
        self.ProcessedPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProcessedPage.sizePolicy().hasHeightForWidth())
        self.ProcessedPage.setSizePolicy(sizePolicy)
        self.ProcessedPage.setObjectName("ProcessedPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ProcessedPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SpatialCorrLine = QtWidgets.QLineEdit(self.ProcessedPage)
        self.SpatialCorrLine.setMinimumSize(QtCore.QSize(0, 50))
        self.SpatialCorrLine.setObjectName("SpatialCorrLine")
        self.gridLayout_4.addWidget(self.SpatialCorrLine, 2, 2, 1, 1)
        self.SpatialValLine = QtWidgets.QLineEdit(self.ProcessedPage)
        self.SpatialValLine.setMinimumSize(QtCore.QSize(0, 50))
        self.SpatialValLine.setObjectName("SpatialValLine")
        self.gridLayout_4.addWidget(self.SpatialValLine, 2, 3, 1, 1)
        self.EffValLine = QtWidgets.QLineEdit(self.ProcessedPage)
        self.EffValLine.setMinimumSize(QtCore.QSize(150, 50))
        self.EffValLine.setObjectName("EffValLine")
        self.gridLayout_4.addWidget(self.EffValLine, 1, 3, 1, 1)
        self.EffResLine = QtWidgets.QLineEdit(self.ProcessedPage)
        self.EffResLine.setMinimumSize(QtCore.QSize(0, 50))
        self.EffResLine.setObjectName("EffResLine")
        self.gridLayout_4.addWidget(self.EffResLine, 1, 2, 1, 1)
        self.Set2 = QtWidgets.QPushButton(self.ProcessedPage)
        self.Set2.setMinimumSize(QtCore.QSize(150, 50))
        self.Set2.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.Set2.setObjectName("Set2")
        self.gridLayout_4.addWidget(self.Set2, 2, 4, 1, 1)
        self.ExecuteBttn = QtWidgets.QPushButton(self.ProcessedPage)
        self.ExecuteBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.ExecuteBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.ExecuteBttn.setObjectName("ExecuteBttn")
        self.gridLayout_4.addWidget(self.ExecuteBttn, 0, 3, 1, 2)
        self.NextGraph = QtWidgets.QPushButton(self.ProcessedPage)
        self.NextGraph.setMinimumSize(QtCore.QSize(0, 50))
        self.NextGraph.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.NextGraph.setObjectName("NextGraph")
        self.gridLayout_4.addWidget(self.NextGraph, 3, 1, 1, 1)
        self.PregGraph = QtWidgets.QPushButton(self.ProcessedPage)
        self.PregGraph.setMinimumSize(QtCore.QSize(0, 50))
        self.PregGraph.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.PregGraph.setObjectName("PregGraph")
        self.gridLayout_4.addWidget(self.PregGraph, 3, 0, 1, 1)
        self.Set1 = QtWidgets.QPushButton(self.ProcessedPage)
        self.Set1.setMinimumSize(QtCore.QSize(150, 50))
        self.Set1.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.Set1.setObjectName("Set1")
        self.gridLayout_4.addWidget(self.Set1, 1, 4, 1, 1)
        self.GraphLabel = QtWidgets.QLabel(self.ProcessedPage)
        self.GraphLabel.setMinimumSize(QtCore.QSize(512, 512))
        self.GraphLabel.setMaximumSize(QtCore.QSize(1024, 1024))
        self.GraphLabel.setText("")
        self.GraphLabel.setObjectName("GraphLabel")
        self.gridLayout_4.addWidget(self.GraphLabel, 0, 0, 3, 2)
        self.PagesWidget.addWidget(self.ProcessedPage)
        self.SegmentPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SegmentPage.sizePolicy().hasHeightForWidth())
        self.SegmentPage.setSizePolicy(sizePolicy)
        self.SegmentPage.setObjectName("SegmentPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SegmentPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SegmentedLabel = QtWidgets.QLabel(self.SegmentPage)
        self.SegmentedLabel.setMinimumSize(QtCore.QSize(512, 512))
        self.SegmentedLabel.setText("")
        self.SegmentedLabel.setObjectName("SegmentedLabel")
        self.gridLayout_2.addWidget(self.SegmentedLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.BeginBttn = QtWidgets.QPushButton(self.SegmentPage)
        self.BeginBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.BeginBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.BeginBttn.setObjectName("BeginBttn")
        self.gridLayout_2.addWidget(self.BeginBttn, 0, 5, 1, 1)
        self.PriorStepBttn = QtWidgets.QPushButton(self.SegmentPage)
        self.PriorStepBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.PriorStepBttn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.PriorStepBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.PriorStepBttn.setObjectName("PriorStepBttn")
        self.gridLayout_2.addWidget(self.PriorStepBttn, 1, 0, 1, 1)
        self.NextStepBttn = QtWidgets.QPushButton(self.SegmentPage)
        self.NextStepBttn.setMinimumSize(QtCore.QSize(0, 50))
        self.NextStepBttn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.NextStepBttn.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 199, 178);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(171, 73, 101);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(213, 72, 89);\n"
"}")
        self.NextStepBttn.setObjectName("NextStepBttn")
        self.gridLayout_2.addWidget(self.NextStepBttn, 1, 1, 1, 1)
        self.PagesWidget.addWidget(self.SegmentPage)
        self.verticalLayout_5.addWidget(self.PagesWidget, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.PagesFrame)
        self.verticalLayout_2.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("background-color: rgb(60, 63, 83);\n"
"color: rgb(250, 199, 178);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.PagesWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MenuBttn.setText(_translate("MainWindow", "MENU"))
        self.SettingBttn.setText(_translate("MainWindow", "SETTINGS"))
        self.MenuBrowse.setText(_translate("MainWindow", "Browse"))
        self.MenuProcess.setText(_translate("MainWindow", "PreProcess"))
        self.MenuAnal.setText(_translate("MainWindow", "Analyise"))
        self.MenuSegment.setText(_translate("MainWindow", "Segment"))
        self.BrowseBttn_2.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "E.g.: C:/Users/User1/Documents"))
        self.label_2.setText(_translate("MainWindow", "Change Output Directory"))
        self.BrowseBttn.setText(_translate("MainWindow", "Browse"))
        self.LoadBttn.setText(_translate("MainWindow", "Load"))
        self.DAPIBttn.setText(_translate("MainWindow", "DAPI"))
        self.StartBttn.setText(_translate("MainWindow", "Start"))
        self.AlxBttn.setText(_translate("MainWindow", "Alx647"))
        self.PrevStepBttn.setText(_translate("MainWindow", "Previous"))
        self.ForwStepBttn.setText(_translate("MainWindow", "Next"))
        self.SpatialCorrLine.setText(_translate("MainWindow", "Threshold for Spatial Correlation"))
        self.EffResLine.setText(_translate("MainWindow", "Threshold for Effective Resolution"))
        self.Set2.setText(_translate("MainWindow", "Set"))
        self.ExecuteBttn.setText(_translate("MainWindow", "Start"))
        self.NextGraph.setText(_translate("MainWindow", "Next"))
        self.PregGraph.setText(_translate("MainWindow", "Prev"))
        self.Set1.setText(_translate("MainWindow", "Set"))
        self.BeginBttn.setText(_translate("MainWindow", "Start"))
        self.PriorStepBttn.setText(_translate("MainWindow", "Previous"))
        self.NextStepBttn.setText(_translate("MainWindow", "Next"))
